<?php
if ( !defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly
}

// Header Setings
CSF::createSection( $rezillaThemeOption, array(
    'id'    => 'rezilla_header_settings',
    'title' => esc_html__( 'Header Settings', 'rezilla' ),
    'icon'  => 'fa fa-header',
    'fields' => array(
        array(
            'id'       => 'rezilla_header_styles',
            'type'     => 'image_select',
            'title'    => esc_html__( 'Select Style', 'rezilla' ),
            'options'  => array(
                'one'   => get_theme_file_uri( 'assets/image/header-1.jpg' ),
                'two'   => get_theme_file_uri( 'assets/image/header-2.jpg' ),
                'three' => get_theme_file_uri( 'assets/image/header-3.jpg' ),
                'four' => get_theme_file_uri( 'assets/image/header-4.jpg' ),
            ),
            'default'  => 'one',
            'subtitle' => esc_html__( 'Choose Your Header Style For Global', 'rezilla' ),
        ),
        /////////////////////////////////////
        ////////// HEADER DESIGN ONE ////////
        ////////////////////////////////////
        array(
            'type'    => 'subheading',
            'content' => esc_html__( 'Sticky Menu Options', 'rezilla' ),
        ),
        array(
            'id'         => 'rezilla_enable_sticky_menu',
            'type'       => 'switcher',
            'title'      => esc_html__( 'Enable Sticky Menu', 'rezilla' ),
            'subtitle'   => esc_html__( 'Enable Sticky Menu If you need', 'rezilla' ),
            'default'    => false,
            'text_on'    => esc_html__( 'Enabled', 'rezilla' ),
            'text_off'   => esc_html__( 'Disabled', 'rezilla' ),
            'text_width' => 100,
        ),
        array(
            'id'         => 'rezilla_header_sticky',
            'type'       => 'color',
            'title'      => esc_html__( 'Sticky Menu Background', 'rezilla' ),
            'subtitle'   => esc_html__( 'Add Background Color for Sticky Menu', 'rezilla' ),
            'output_mode' => 'background-color',
            'output'     => '.header-one .sticky-bar',
            'output_important' => true,
            'dependency' => array(
                array( 'rezilla_header_styles', '==', 'one','all' ),
                array( 'rezilla_enable_sticky_menu',   '==', 'true' ),
            ),
        ),
        array(
            'id'         => 'rezilla_header_sticky2',
            'type'       => 'color',
            'title'      => esc_html__( 'Sticky Menu Background', 'rezilla' ),
            'subtitle'   => esc_html__( 'Add Background Color for Sticky Menu', 'rezilla' ),
            'output_mode' => 'background-color',
            'output'     => '.header-two .sticky-bar',
            'output_important' => true,
            'dependency' => array(
                array( 'rezilla_header_styles', '==', 'two','all' ),
                array( 'rezilla_enable_sticky_menu',   '==', 'true' ),
            ),
        ),
        array(
            'id'         => 'rezilla_header_sticky3',
            'type'       => 'color',
            'title'      => esc_html__( 'Sticky Menu Background', 'rezilla' ),
            'subtitle'   => esc_html__( 'Add Background Color for Sticky Menu', 'rezilla' ),
            'output_mode' => 'background-color',
            'output'     => '.header-three .sticky-bar',
            'output_important' => true,
            'dependency' => array(
                array( 'rezilla_header_styles', '==', 'three','all' ),
                array( 'rezilla_enable_sticky_menu',   '==', 'true' ),
            ),
        ),
        array(
            'id'         => 'rezilla_header_sticky4',
            'type'       => 'color',
            'title'      => esc_html__( 'Sticky Menu Background', 'rezilla' ),
            'subtitle'   => esc_html__( 'Add Background Color for Sticky Menu', 'rezilla' ),
            'output_mode' => 'background-color',
            'output'     => '.header-four .sticky-bar',
            'output_important' => true,
            'dependency' => array(
                array( 'rezilla_header_styles', '==', 'four','all' ),
                array( 'rezilla_enable_sticky_menu',   '==', 'true' ),
            ),
        ),
        array(
            'type'    => 'subheading',
            'content' => esc_html__( 'Site Logo Options', 'rezilla' ),
            'dependency' => array(
                array( 'rezilla_header_styles', '==', 'one','all' ),
            ),
        ),
        array(
            'id'         => 'rezilla_show_hlogo1',
            'type'       => 'switcher',
            'title'      => esc_html__( 'Enable Logo', 'rezilla' ),
            'subtitle'   => esc_html__( 'Enable Logo Options if you need', 'rezilla' ),
            'default'    => true,
            'text_on'    => esc_html__( 'Enabled', 'rezilla' ),
            'text_off'   => esc_html__( 'Disabled', 'rezilla' ),
            'text_width' => 100,
            'dependency' => array( 'rezilla_header_styles', '==', 'one', 'all' ),
        ),
        array(
            'id'         => 'rezilla_logo1',
            'type'       => 'media',
            'title'      => esc_html__( 'SIte Logo', 'rezilla' ),
            'subtitle'   => esc_html__( 'Upload Header Logo if you do not use Wordpress Default logo option ', 'rezilla' ),
            'library'    => 'image',
            'dependency' => array( 'rezilla_header_styles|rezilla_show_hlogo1', '==|==', 'one|true', 'all' ),
        ),
        array(
            'id'          => 'rezilla_logo1_size',
            'type'        => 'number',
            'title'       => esc_html__( 'Logo Size', 'rezilla' ),
            'subtitle'       => esc_html__( 'Add logo Size if you need Logo Size', 'rezilla' ),
            'unit'        => 'px',
            'output'      => '.header-one .site-branding img',
            'output_mode' => 'width',
            'dependency'  => array( 'rezilla_header_styles', '==', 'one', 'all' ),
        ),
        array(
            'type'       => 'subheading',
            'content'    => esc_html__( 'Header Menu Options', 'rezilla' ),
            'dependency' => array( 'rezilla_header_styles', '==', 'one', 'all' ),
        ),
        array(
            'id'     => 'rezilla_header-menu_group1',
            'type'   => 'fieldset',
            'title'  => esc_html__( 'Site Header Options', 'rezilla' ),
            'subtitle'  => esc_html__( 'Add your Site Header Options here', 'rezilla' ),
            'dependency' => array( 'rezilla_header_styles', '==', 'one', 'all' ),
            'fields' => array(
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Parent Menu Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_top_header1_menu_ncolors',
                    'type'       => 'link_color',
                    'title'      => esc_html__( 'Menu Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Nav Menu Normal and Hover Color', 'rezilla' ),
                    'output'     => '.header-one .main-navigation ul li a',
                ),
                array(
                    'id'         => 'rezilla_header1_menu_bg',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Background Color for Menu Area', 'rezilla' ),
                    'output'     => '.header-one .main-header',
                ),
                array(
                    'id'         => 'rezilla_header_border_color1',
                    'type'       => 'color',
                    'title'      => esc_html__( 'border Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For menu Border', 'rezilla' ),
                    'output'     => '.site-header.header-one',
                    'output_mode' => 'border-color',
                ),
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Sub menu Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_submenu_color1',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Text Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Sub Menu Text', 'rezilla' ),
                    'output'     => '.main-navigation ul li ul li a',
                ),
                array(
                    'id'         => 'rezilla_header_submenu_bgcolor1',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Background Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Sub Menu Text', 'rezilla' ),
                    'output'     => '.main-navigation ul li ul',
                    'output_mode' => 'background-color',
                ),
                array(
                    'type'    => 'notice',
                    'style'   => 'success',
                    'content' =>  esc_html__( 'Sub Menu Hover CSS', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_submenu_hcolor1',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Text Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Sub Menu Text', 'rezilla' ),
                    'output'     => '.header-one .main-navigation ul li ul li a:hover',
                ),
                array(
                    'id'         => 'rezilla_header_submenu_hbgcolor1',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Background Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Sub Menu Text', 'rezilla' ),
                    'output'     => '.header-one .main-navigation ul li ul li a:hover',
                    'output_mode' => 'background-color',
                ),
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Header Menu Attribute Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_menu_attribute_c',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Text Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Menu Attribute Text', 'rezilla' ),
                    'output_mode' => 'color',
                    'output'     => '.navbar ul li a[title]:after',
                    'output_important' => true
                ),
                array(
                    'id'         => 'rezilla_header_menu_attribute_bg',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Background Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Background Color For Menu Attribute', 'rezilla' ),
                    'output_mode' => 'background-color',
                    'output'     => '.navbar ul li a[title]:after',
                    'output_important' => true
                ),
                array(
                    'id'         => 'rezilla_header_menu_attribute_border',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Symble Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Symble Color For Menu Attribute', 'rezilla' ),
                    'output_mode' => 'border-left-color',
                    'output'     => '.navbar ul li a[title]:before',
                    'output_important' => true
                ),
            ),
        ),
        array(
            'type'    => 'subheading',
            'content' => esc_html__( 'Site Logo Options', 'rezilla' ),
            'dependency' => array(
                array( 'rezilla_header_styles', '==', 'two','all' ),
            ),
        ),
        array(
            'id'         => 'rezilla_show_hlogo2',
            'type'       => 'switcher',
            'title'      => esc_html__( 'Enable Logo', 'rezilla' ),
            'subtitle'   => esc_html__( 'Enable Logo Options if you need', 'rezilla' ),
            'default'    => true,
            'text_on'    => esc_html__( 'Enabled', 'rezilla' ),
            'text_off'   => esc_html__( 'Disabled', 'rezilla' ),
            'text_width' => 100,
            'dependency' => array( 'rezilla_header_styles', '==', 'two', 'all' ),
        ),
        array(
            'id'         => 'rezilla_logo2',
            'type'       => 'media',
            'title'      => esc_html__( 'SIte Logo', 'rezilla' ),
            'subtitle'   => esc_html__( 'Upload Header Logo if you do not use Wordpress Default logo option ', 'rezilla' ),
            'library'    => 'image',
            'dependency' => array( 'rezilla_header_styles|rezilla_show_hlogo2', '==|==', 'two|true', 'all' ),
        ),
        array(
            'id'          => 'rezilla_logo2_size',
            'type'        => 'number',
            'title'       => esc_html__( 'Logo Size', 'rezilla' ),
            'subtitle'       => esc_html__( 'Add logo Size if you need Logo Size', 'rezilla' ),
            'unit'        => 'px',
            'output'      => '.header-two .site-branding img',
            'output_mode' => 'width',
            'dependency'  => array( 'rezilla_header_styles', '==', 'two', 'all' ),
        ),
        ////// HEADER STYLE TWO 
        array(
            'id'     => 'rezilla_header-menu_group2',
            'type'   => 'fieldset',
            'title'  => esc_html__( 'Site Header Options', 'rezilla' ),
            'subtitle'  => esc_html__( 'Add your Site Header Options here', 'rezilla' ),
            'dependency' => array( 'rezilla_header_styles', '==', 'two', 'all' ),
            'fields' => array(
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Parent Menu Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_top_header2_menu_ncolors',
                    'type'       => 'link_color',
                    'title'      => esc_html__( 'Menu Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Nav Menu Normal and Hover Color', 'rezilla' ),
                    'output'     => '.header-two .main-navigation ul li a',
                ),
                array(
                    'id'         => 'rezilla_header2_menu_bg',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Background Color for Menu Area', 'rezilla' ),
                    'output'     => '.header-two .main-header',
                ),
                array(
                    'id'         => 'rezilla_header_border_color2',
                    'type'       => 'color',
                    'title'      => esc_html__( 'border Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For menu Border', 'rezilla' ),
                    'output'     => '.site-header.header-two',
                    'output_mode' => 'border-color',
                ),
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Sub menu Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_submenu_color2',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Text Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Sub Menu Text', 'rezilla' ),
                    'output'     => '.header-two .main-navigation ul li ul li a',
                ),
                array(
                    'id'         => 'rezilla_header_submenu_bgcolor2',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Background Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Sub Menu Text', 'rezilla' ),
                    'output'     => '.header-two .main-navigation ul li ul',
                    'output_mode' => 'background-color',
                ),
                array(
                    'type'    => 'notice',
                    'style'   => 'success',
                    'content' =>  esc_html__( 'Sub Menu Hover CSS', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_submenu_hcolor2',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Text Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Sub Menu Text', 'rezilla' ),
                    'output'     => '.header-two .main-navigation ul li ul li a:hover',
                ),
                array(
                    'id'         => 'rezilla_header_submenu_hbgcolor2',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Background Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Sub Menu Text', 'rezilla' ),
                    'output'     => '.header-two .main-navigation ul li ul li a:hover',
                    'output_mode' => 'background-color',
                ),
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Header Menu Attribute Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_menu_attribute_c2',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Text Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Menu Attribute Text', 'rezilla' ),
                    'output_mode' => 'color',
                    'output'     => '.header-two .navbar ul li a[title]:after',
                    'output_important' => true
                ),
                array(
                    'id'         => 'rezilla_header_menu_attribute_bg2',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Background Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Background Color For Menu Attribute', 'rezilla' ),
                    'output_mode' => 'background-color',
                    'output'     => '.header-two .navbar ul li a[title]:after',
                    'output_important' => true
                ),
                array(
                    'id'         => 'rezilla_header_menu_attribute_border2',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Symble Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Symble Color For Menu Attribute', 'rezilla' ),
                    'output_mode' => 'border-left-color',
                    'output'     => '.header-two .navbar ul li a[title]:before',
                    'output_important' => true
                ),
            ),
        ),
        ////////////// HEADER STYLE THREE
        array(
            'id'         => 'rezilla_show_hlogo3',
            'type'       => 'switcher',
            'title'      => esc_html__( 'Enable Logo', 'rezilla' ),
            'subtitle'   => esc_html__( 'Enable Logo Options if you need', 'rezilla' ),
            'default'    => true,
            'text_on'    => esc_html__( 'Enabled', 'rezilla' ),
            'text_off'   => esc_html__( 'Disabled', 'rezilla' ),
            'text_width' => 100,
            'dependency' => array( 'rezilla_header_styles', '==', 'three', 'all' ),
        ),
        array(
            'id'         => 'rezilla_logo3',
            'type'       => 'media',
            'title'      => esc_html__( 'SIte Logo', 'rezilla' ),
            'subtitle'   => esc_html__( 'Upload Header Logo if you do not use Wordpress Default logo option ', 'rezilla' ),
            'library'    => 'image',
            'dependency' => array( 'rezilla_header_styles|rezilla_show_hlogo3', '==|==', 'three|true', 'all' ),
        ),
        array(
            'id'          => 'rezilla_logo3_size',
            'type'        => 'number',
            'title'       => esc_html__( 'Logo Size', 'rezilla' ),
            'subtitle'       => esc_html__( 'Add logo Size if you need Logo Size', 'rezilla' ),
            'unit'        => 'px',
            'output'      => '.header-three .site-branding img',
            'output_mode' => 'width',
            'dependency'  => array( 'rezilla_header_styles', '==', 'three', 'all' ),
        ),

        array(
            'id'     => 'rezilla_header-menu_group3',
            'type'   => 'fieldset',
            'title'  => esc_html__( 'Site Header Options', 'rezilla' ),
            'subtitle'  => esc_html__( 'Add your Site Header Options here', 'rezilla' ),
            'dependency' => array( 'rezilla_header_styles', '==', 'three', 'all' ),
            'fields' => array(
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Parent Menu Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_top_header3_menu_ncolors',
                    'type'       => 'link_color',
                    'title'      => esc_html__( 'Menu Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Nav Menu Normal and Hover Color', 'rezilla' ),
                    'output'     => '.header-three .main-navigation ul li a',
                ),
                array(
                    'id'         => 'rezilla_header3_menu_bg',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Background Color for Menu Area', 'rezilla' ),
                    'output'     => '.header-three .main-header',
                ),
                array(
                    'id'         => 'rezilla_header_border_color3',
                    'type'       => 'color',
                    'title'      => esc_html__( 'border Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For menu Border', 'rezilla' ),
                    'output'     => '.site-header.header-three',
                    'output_mode' => 'border-color',
                ),
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Sub menu Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_submenu_color3',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Text Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Sub Menu Text', 'rezilla' ),
                    'output'     => '.header-three .main-navigation ul li ul li a',
                ),
                array(
                    'id'         => 'rezilla_header_submenu_bgcolor3',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Background Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Sub Menu Text', 'rezilla' ),
                    'output'     => '.header-three .main-navigation ul li ul',
                    'output_mode' => 'background-color',
                ),
                array(
                    'type'    => 'notice',
                    'style'   => 'success',
                    'content' =>  esc_html__( 'Sub Menu Hover CSS', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_submenu_hcolor3',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Text Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Sub Menu Text', 'rezilla' ),
                    'output'     => '.header-three .main-navigation ul li ul li a:hover',
                ),
                array(
                    'id'         => 'rezilla_header_submenu_hbgcolor3',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Background Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Sub Menu Text', 'rezilla' ),
                    'output'     => '.header-three .main-navigation ul li ul li a:hover',
                    'output_mode' => 'background-color',
                ),
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Header Menu Attribute Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_menu_attribute_c3',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Text Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Menu Attribute Text', 'rezilla' ),
                    'output_mode' => 'color',
                    'output'     => '.header-three .navbar ul li a[title]:after',
                    'output_important' => true
                ),
                array(
                    'id'         => 'rezilla_header_menu_attribute_bg3',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Background Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Background Color For Menu Attribute', 'rezilla' ),
                    'output_mode' => 'background-color',
                    'output'     => '.header-three .navbar ul li a[title]:after',
                    'output_important' => true
                ),
                array(
                    'id'         => 'rezilla_header_menu_attribute_border3',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Symble Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Symble Color For Menu Attribute', 'rezilla' ),
                    'output_mode' => 'border-left-color',
                    'output'     => '.header-three .navbar ul li a[title]:before',
                    'output_important' => true
                ),
            ),
        ),
        ///////// HEADER STYLE FOUR 
        array(
            'id'         => 'rezilla_show_hlogo4',
            'type'       => 'switcher',
            'title'      => esc_html__( 'Enable Logo', 'rezilla' ),
            'subtitle'   => esc_html__( 'Enable Logo Options if you need', 'rezilla' ),
            'default'    => true,
            'text_on'    => esc_html__( 'Enabled', 'rezilla' ),
            'text_off'   => esc_html__( 'Disabled', 'rezilla' ),
            'text_width' => 100,
            'dependency' => array( 'rezilla_header_styles', '==', 'four', 'all' ),
        ),
        array(
            'id'         => 'rezilla_logo4',
            'type'       => 'media',
            'title'      => esc_html__( 'SIte Logo', 'rezilla' ),
            'subtitle'   => esc_html__( 'Upload Header Logo if you do not use Wordpress Default logo option ', 'rezilla' ),
            'library'    => 'image',
            'dependency' => array( 'rezilla_header_styles|rezilla_show_hlogo4', '==|==', 'four|true', 'all' ),
        ),
        array(
            'id'          => 'rezilla_logo4_size',
            'type'        => 'number',
            'title'       => esc_html__( 'Logo Size', 'rezilla' ),
            'subtitle'       => esc_html__( 'Add logo Size if you need Logo Size', 'rezilla' ),
            'unit'        => 'px',
            'output'      => '.header-four .site-branding img',
            'output_mode' => 'width',
            'dependency'  => array( 'rezilla_header_styles', '==', 'four', 'all' ),
        ),
        array(
            'id'     => 'rezilla_header-menu_group4',
            'type'   => 'fieldset',
            'title'  => esc_html__( 'Site Header Options', 'rezilla' ),
            'subtitle'  => esc_html__( 'Add your Site Header Options here', 'rezilla' ),
            'dependency' => array( 'rezilla_header_styles', '==', 'four', 'all' ),
            'fields' => array(
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Parent Menu Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_top_header4_menu_ncolors',
                    'type'       => 'link_color',
                    'title'      => esc_html__( 'Menu Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Nav Menu Normal and Hover Color', 'rezilla' ),
                    'output'     => '.header-four .main-navigation ul li a',
                ),
                array(
                    'id'         => 'rezilla_header4_menu_bg',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Background Color for Menu Area', 'rezilla' ),
                    'output'     => '.header-four .main-header',
                ),
                array(
                    'id'         => 'rezilla_header_border_color4',
                    'type'       => 'color',
                    'title'      => esc_html__( 'border Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For menu Border', 'rezilla' ),
                    'output'     => '.site-header.header-four',
                    'output_mode' => 'border-color',
                ),
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Sub menu Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_submenu_color4',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Text Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Sub Menu Text', 'rezilla' ),
                    'output'     => '.header-four .main-navigation ul li ul li a',
                ),
                array(
                    'id'         => 'rezilla_header_submenu_bgcolor4',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Background Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Sub Menu Text', 'rezilla' ),
                    'output'     => '.header-four .main-navigation ul li ul',
                    'output_mode' => 'background-color',
                ),
                array(
                    'type'    => 'notice',
                    'style'   => 'success',
                    'content' =>  esc_html__( 'Sub Menu Hover CSS', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_submenu_hcolor4',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Text Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Sub Menu Text', 'rezilla' ),
                    'output'     => '.header-four .main-navigation ul li ul li a:hover',
                ),
                array(
                    'id'         => 'rezilla_header_submenu_hbgcolor4',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Background Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Sub Menu Text', 'rezilla' ),
                    'output'     => '.header-four .main-navigation ul li ul li a:hover',
                    'output_mode' => 'background-color',
                ),
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Header Menu Attribute Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_menu_attribute_c4',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Text Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Color For Menu Attribute Text', 'rezilla' ),
                    'output_mode' => 'color',
                    'output'     => '.header-four .navbar ul li a[title]:after',
                    'output_important' => true
                ),
                array(
                    'id'         => 'rezilla_header_menu_attribute_bg4',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Background Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Background Color For Menu Attribute', 'rezilla' ),
                    'output_mode' => 'background-color',
                    'output'     => '.header-four .navbar ul li a[title]:after',
                    'output_important' => true
                ),
                array(
                    'id'         => 'rezilla_header_menu_attribute_border4',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Symble Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Symble Color For Menu Attribute', 'rezilla' ),
                    'output_mode' => 'border-left-color',
                    'output'     => '.header-four .navbar ul li a[title]:before',
                    'output_important' => true
                ),
            ),
        ),
        //////////////////////////////////////////////////////
        ///////// Header SignUp and Search Button ///////////
        ////////////////////////////////////////////////////
        array(
            'type'       => 'subheading',
            'content'    => esc_html__( 'Header Button Options', 'rezilla' ),
        ),
        array(
            'id'         => 'rezilla_header_enable_cta',
            'type'       => 'switcher',
            'title'      => esc_html__( 'Enable Button', 'rezilla' ),
            'subtitle'   =>esc_html__( 'Enable Header SignUp Button', 'rezilla' ),
            'text_on'    => esc_html__( 'Enabled', 'rezilla' ),
            'text_off'   => esc_html__( 'Disabled', 'rezilla' ),
            'text_width' => 100,
            'default'    => true,
        ),
        array(
            'id'      => 'rezilla_header_cta_text',
            'type'    => 'text',
            'title'   => esc_html__( 'Button Text', 'rezilla' ),
            'default' => esc_html__( 'Sign Up', 'rezilla' ),
            'dependency' => array( 'rezilla_header_enable_cta', '==', 'true' ),
        ),
        array(
            'id'       => 'rezilla_header_cta_link',
            'type'     => 'link',
            'title'    =>esc_html__( 'Button Link', 'rezilla' ),
            'subtitle'    =>esc_html__( 'Add your Button Link Here', 'rezilla' ),
            'dependency' => array( 'rezilla_header_enable_cta', '==', 'true' ),
            'default'  => array(
              'url'    => '#',
              'text'   =>  esc_html__( 'Rezilla Wordpress Theme', 'rezilla' ),
              'target' => '_blank',
            ),
            'dependency' => array( 'rezilla_header_enable_cta', '==', 'true' ),
        ),
        //// Style for header button one
        array(
            'id'     => 'rezilla_header_button_group1',
            'type'   => 'fieldset',
            'title'  => esc_html__( 'Header Buttons Options', 'rezilla' ),
            'subtitle'  => esc_html__( 'Add your Header Buttons Options here', 'rezilla' ),
            'dependency' => array(
                array( 'rezilla_header_styles', '==', 'one','all' ),
                array( 'rezilla_header_enable_cta',   '==', 'true' ),
            ),
            'fields' => array(
                array(
                    'id'         => 'rezilla_header_btn_color',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Button Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Color for Header Singup Button Text', 'rezilla' ),
                    'output'     => '.header-one .button.header-btn .theme-btns',
                ),
                array(
                    'id'         => 'rezilla_header_btn_bg',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Background Color for Header Singup Button', 'rezilla' ),
                    'background_gradient'    => true,
                    'background_image'       => false,
                    'background_position'    => false,
                    'background_repeat'      => false,
                    'background_attachment'  => false,
                    'background_size'        => false,
                    'output'     => '.header-one .button.header-btn .theme-btns',
                ),
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Hover Color Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_btn_hcolor',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Button Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Color for Header Singup Button Text', 'rezilla' ),
                    'output'     => '.header-one .button.header-btn .theme-btns:hover',
                ),
                array(
                    'id'         => 'rezilla_header_btn_hbg',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Background Color for Header Singup Button', 'rezilla' ),
                    'background_gradient'    => true,
                    'background_image'       => false,
                    'background_position'    => false,
                    'background_repeat'      => false,
                    'background_attachment'  => false,
                    'background_size'        => false,
                    'output'     => '.header-one .button.header-btn .theme-btns:hover',
                ),
            ),
        ),
        ////////// HEADER BUTTON STYLE TWO 
        array(
            'id'     => 'rezilla_header_button_group2',
            'type'   => 'fieldset',
            'title'  => esc_html__( 'Header Buttons Options', 'rezilla' ),
            'subtitle'  => esc_html__( 'Add your Header Buttons Options here', 'rezilla' ),
            'dependency' => array(
                array( 'rezilla_header_styles', '==', 'two','all' ),
                array( 'rezilla_header_enable_cta',   '==', 'true' ),
            ),
            'fields' => array(
                array(
                    'id'         => 'rezilla_header_btn_color2',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Button Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Color for Header Singup Button Text', 'rezilla' ),
                    'output'     => '.header-two .button.header-btn .theme-btns',
                ),
                array(
                    'id'         => 'rezilla_header_btn_bg2',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Background Color for Header Singup Button', 'rezilla' ),
                    'background_gradient'    => true,
                    'background_image'       => false,
                    'background_position'    => false,
                    'background_repeat'      => false,
                    'background_attachment'  => false,
                    'background_size'        => false,
                    'output'     => '.header-two .button.header-btn .theme-btns',
                ),
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Hover Color Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_btn_hcolor2',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Button Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Color for Header Singup Button Text', 'rezilla' ),
                    'output'     => '.header-two .button.header-btn .theme-btns:hover',
                ),
                array(
                    'id'         => 'rezilla_header_btn_hbg2',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Background Color for Header Singup Button', 'rezilla' ),
                    'background_gradient'    => true,
                    'background_image'       => false,
                    'background_position'    => false,
                    'background_repeat'      => false,
                    'background_attachment'  => false,
                    'background_size'        => false,
                    'output'     => '.header-two .button.header-btn .theme-btns:hover',
                ),
            ),
        ),
        ////////// HEADER BUTTON STYLE THREE 
        array(
            'id'     => 'rezilla_header_button_group3',
            'type'   => 'fieldset',
            'title'  => esc_html__( 'Header Buttons Options', 'rezilla' ),
            'subtitle'  => esc_html__( 'Add your Header Buttons Options here', 'rezilla' ),
            'dependency' => array(
                array( 'rezilla_header_styles', '==', 'three','all' ),
                array( 'rezilla_header_enable_cta',   '==', 'true' ),
            ),
            'fields' => array(
                array(
                    'id'         => 'rezilla_header_btn_color3',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Button Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Color for Header Singup Button Text', 'rezilla' ),
                    'output'     => '.header-three .button.header-btn .theme-btns',
                ),
                array(
                    'id'         => 'rezilla_header_btn_bg3',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Background Color for Header Singup Button', 'rezilla' ),
                    'background_gradient'    => true,
                    'background_image'       => false,
                    'background_position'    => false,
                    'background_repeat'      => false,
                    'background_attachment'  => false,
                    'background_size'        => false,
                    'output'     => '.header-three .button.header-btn .theme-btns',
                ),
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Hover Color Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_btn_hcolor3',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Button Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Color for Header Singup Button Text', 'rezilla' ),
                    'output'     => '.header-three .button.header-btn .theme-btns:hover',
                ),
                array(
                    'id'         => 'rezilla_header_btn_hbg3',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Background Color for Header Singup Button', 'rezilla' ),
                    'background_gradient'    => true,
                    'background_image'       => false,
                    'background_position'    => false,
                    'background_repeat'      => false,
                    'background_attachment'  => false,
                    'background_size'        => false,
                    'output'     => '.header-three .button.header-btn .theme-btns:hover',
                ),
            ),
        ),
        ////////// HEADER BUTTON STYLE FOUR
        array(
            'id'     => 'rezilla_header_button_group4',
            'type'   => 'fieldset',
            'title'  => esc_html__( 'Header Buttons Options', 'rezilla' ),
            'subtitle'  => esc_html__( 'Add your Header Buttons Options here', 'rezilla' ),
            'dependency' => array(
                array( 'rezilla_header_styles', '==', 'four','all' ),
                array( 'rezilla_header_enable_cta',   '==', 'true' ),
            ),
            'fields' => array(
                array(
                    'id'         => 'rezilla_header_btn_color4',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Button Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Color for Header Singup Button Text', 'rezilla' ),
                    'output'     => '.header-four .button.header-btn .theme-btns',
                ),
                array(
                    'id'         => 'rezilla_header_btn_bg4',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Background Color for Header Singup Button', 'rezilla' ),
                    'background_gradient'    => true,
                    'background_image'       => false,
                    'background_position'    => false,
                    'background_repeat'      => false,
                    'background_attachment'  => false,
                    'background_size'        => false,
                    'output'     => '.header-four .button.header-btn .theme-btns',
                ),
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Hover Color Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_btn_hcolor4',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Button Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Color for Header Singup Button Text', 'rezilla' ),
                    'output'     => '.header-four .button.header-btn .theme-btns:hover',
                ),
                array(
                    'id'         => 'rezilla_header_btn_hbg4',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Background Color for Header Singup Button', 'rezilla' ),
                    'background_gradient'    => true,
                    'background_image'       => false,
                    'background_position'    => false,
                    'background_repeat'      => false,
                    'background_attachment'  => false,
                    'background_size'        => false,
                    'output'     => '.header-four .button.header-btn .theme-btns:hover',
                ),
            ),
        ), 
        array(
            'type'       => 'subheading',
            'content'    => esc_html__( 'Header Search Options', 'rezilla' ),
        ),
        array(
            'id'         => 'rezilla_header_enable_search',
            'type'       => 'switcher',
            'title'      => esc_html__( 'Enable Search', 'rezilla' ),
            'subtitle'   =>esc_html__( 'Enable Header Search Button Here', 'rezilla' ),
            'text_on'    => esc_html__( 'Enabled', 'rezilla' ),
            'text_off'   => esc_html__( 'Disabled', 'rezilla' ),
            'text_width' => 100,
            'default'    => true,
        ),
        ////////// HEADER SEARCH ONE
        array(
            'id'     => 'rezilla_header_search_group1',
            'type'   => 'fieldset',
            'title'  => esc_html__( 'Header Buttons Options', 'rezilla' ),
            'subtitle'  => esc_html__( 'Add your Header Buttons Options here', 'rezilla' ),
            'dependency' => array(
                array( 'rezilla_header_styles', '==', 'one','all' ),
                array( 'rezilla_header_enable_search',   '==', 'true' ),
            ),
            'fields' => array(
                array(
                    'id'         => 'rezilla_header_search_color',
                    'type'       => 'color',
                    'title'      => esc_html__( 'icon Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Color for Header Singup Button Text', 'rezilla' ),
                    'output'     => '.header-one .button.search-open',
                ),
                array(
                    'id'         => 'rezilla_header_search_bg',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Background Color for Header Singup Button', 'rezilla' ),
                    'background_gradient'    => true,
                    'background_image'       => false,
                    'background_position'    => false,
                    'background_repeat'      => false,
                    'background_attachment'  => false,
                    'background_size'        => false,
                    'output'     => '.header-one .button.search-open',
                ),
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Hover Color Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_search_hcolor',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Button Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Color for Header Singup Button Text', 'rezilla' ),
                    'output'     => '.header-one .button.search-open:hover',
                ),
                array(
                    'id'         => 'rezilla_header_search_hbg',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Background Color for Header Singup Button', 'rezilla' ),
                    'background_gradient'    => true,
                    'background_image'       => false,
                    'background_position'    => false,
                    'background_repeat'      => false,
                    'background_attachment'  => false,
                    'background_size'        => false,
                    'output'     => '.header-one .button.search-open:hover',
                ),
            ),
        ),
        //////// HEADER SEARCH TWO
        array(
            'id'     => 'rezilla_header_search_group2',
            'type'   => 'fieldset',
            'title'  => esc_html__( 'Header Buttons Options', 'rezilla' ),
            'subtitle'  => esc_html__( 'Add your Header Buttons Options here', 'rezilla' ),
            'dependency' => array(
                array( 'rezilla_header_styles', '==', 'two','all' ),
                array( 'rezilla_header_enable_search',   '==', 'true' ),
            ),
            'fields' => array(
                array(
                    'id'         => 'rezilla_header_search_color2',
                    'type'       => 'color',
                    'title'      => esc_html__( 'icon Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Color for Header Singup Button Text', 'rezilla' ),
                    'output'     => '.header-two .button.search-open',
                ),
                array(
                    'id'         => 'rezilla_header_search_bg2',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Background Color for Header Singup Button', 'rezilla' ),
                    'background_gradient'    => true,
                    'background_image'       => false,
                    'background_position'    => false,
                    'background_repeat'      => false,
                    'background_attachment'  => false,
                    'background_size'        => false,
                    'output'     => '.header-two .button.search-open',
                ),
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Hover Color Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_search_hcolor2',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Button Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Color for Header Singup Button Text', 'rezilla' ),
                    'output'     => '.header-two .button.search-open:hover',
                ),
                array(
                    'id'         => 'rezilla_header_search_hbg2',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Background Color for Header Singup Button', 'rezilla' ),
                    'background_gradient'    => true,
                    'background_image'       => false,
                    'background_position'    => false,
                    'background_repeat'      => false,
                    'background_attachment'  => false,
                    'background_size'        => false,
                    'output'     => '.header-two .button.search-open:hover',
                ),
            ),
        ),
        //////// HEADER SEARCH THREE
        array(
            'id'     => 'rezilla_header_search_group3',
            'type'   => 'fieldset',
            'title'  => esc_html__( 'Header Buttons Options', 'rezilla' ),
            'subtitle'  => esc_html__( 'Add your Header Buttons Options here', 'rezilla' ),
            'dependency' => array(
                array( 'rezilla_header_styles', '==', 'three','all' ),
                array( 'rezilla_header_enable_search',   '==', 'true' ),
            ),
            'fields' => array(
                array(
                    'id'         => 'rezilla_header_search_color3',
                    'type'       => 'color',
                    'title'      => esc_html__( 'icon Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Color for Header Singup Button Text', 'rezilla' ),
                    'output'     => '.header-three .button.search-open',
                ),
                array(
                    'id'         => 'rezilla_header_search_bg3',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Background Color for Header Singup Button', 'rezilla' ),
                    'background_gradient'    => true,
                    'background_image'       => false,
                    'background_position'    => false,
                    'background_repeat'      => false,
                    'background_attachment'  => false,
                    'background_size'        => false,
                    'output'     => '.header-three .button.search-open',
                ),
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Hover Color Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_search_hcolor3',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Button Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Color for Header Singup Button Text', 'rezilla' ),
                    'output'     => '.header-three .button.search-open:hover',
                ),
                array(
                    'id'         => 'rezilla_header_search_hbg3',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Background Color for Header Singup Button', 'rezilla' ),
                    'background_gradient'    => true,
                    'background_image'       => false,
                    'background_position'    => false,
                    'background_repeat'      => false,
                    'background_attachment'  => false,
                    'background_size'        => false,
                    'output'     => '.header-three .button.search-open:hover',
                ),
            ),
        ),
        //////// HEADER SEARCH FOUR
        array(
            'id'     => 'rezilla_header_search_group4',
            'type'   => 'fieldset',
            'title'  => esc_html__( 'Header Buttons Options', 'rezilla' ),
            'subtitle'  => esc_html__( 'Add your Header Buttons Options here', 'rezilla' ),
            'dependency' => array(
                array( 'rezilla_header_styles', '==', 'four','all' ),
                array( 'rezilla_header_enable_search',   '==', 'true' ),
            ),
            'fields' => array(
                array(
                    'id'         => 'rezilla_header_search_color4',
                    'type'       => 'color',
                    'title'      => esc_html__( 'icon Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Color for Header Singup Button Text', 'rezilla' ),
                    'output'     => '.header-four .button.search-open',
                ),
                array(
                    'id'         => 'rezilla_header_search_bg4',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Background Color for Header Singup Button', 'rezilla' ),
                    'background_gradient'    => true,
                    'background_image'       => false,
                    'background_position'    => false,
                    'background_repeat'      => false,
                    'background_attachment'  => false,
                    'background_size'        => false,
                    'output'     => '.header-four .button.search-open',
                ),
                array(
                    'type'       => 'submessage',
                    'style'      => 'info',
                    'content'    => esc_html__( 'Hover Color Options', 'rezilla' ),
                ),
                array(
                    'id'         => 'rezilla_header_search_hcolor4',
                    'type'       => 'color',
                    'title'      => esc_html__( 'Button Color', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Color for Header Singup Button Text', 'rezilla' ),
                    'output'     => '.header-four .button.search-open:hover',
                ),
                array(
                    'id'         => 'rezilla_header_search_hbg4',
                    'type'       => 'background',
                    'title'      => esc_html__( 'Background', 'rezilla' ),
                    'subtitle'   => esc_html__( 'Add Your Background Color for Header Singup Button', 'rezilla' ),
                    'background_gradient'    => true,
                    'background_image'       => false,
                    'background_position'    => false,
                    'background_repeat'      => false,
                    'background_attachment'  => false,
                    'background_size'        => false,
                    'output'     => '.header-four .button.search-open:hover',
                ),
            ),
        ),
    ),
) );